config/routes.rb
Todo::Application.routes.draw do
  resources :todos do
    collection do
      get :assets
      post :list
    end
  end

  root :to => 'todos#index'
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = TodoItem.all.reject { |todo| (todo.updated_at > 1.day.ago) && todo.complete }

    respond_to do |f|
      f.html # index.html
      f.json { render :json => @todos }
    end
  end

  def create
    @todo = TodoItem.create(params[:todo])

    if @todo.valid?
      render :json => @todo.as_json
    else
      render :json => @todo.errors, :status => :unprocessable_entity
    end
  end

  def update
    @todo = TodoItem.find(params[:id])

    if @todo.update_attributes(params[:todo])
      render :json => @todo.as_json
    else
      render :json => @todo.errors, :status => :unprocessable_entity
    end
  end

  def assets
    @todos = TodoItem.all

    respond_to do |f|
      f.appcache
    end
  end

  def list
    @todos = TodoItem.all

    respond_to do |f|
      f.html # index.html
      f.json { render :json => @todos.as_json }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def mobile?
    iphone? || android?
  end

  def iphone?
    request.user_agent.include?("iPhone")
  end

  def android?
    request.user_agent.include?("Android")
  end

  def include_appcache?
    !!appcache
  end

  def appcache(name=nil)
    @appcache ||= name if name
    @appcache
  end
end

app/helpers/todos_helper.rb
module TodosHelper
  def appcache_version
    if File.exist?(Rails.root.join('REVISION'))
      File.read(Rails.root.join('REVISION'))
    else
      Process.pid.to_s
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%- if include_appcache? %>
  <html manifest="<%= appcache %>">
<%- else %>
  <html>
<%- end %>
<head>
  <title>Todo</title>
  <%= javascript_include_tag 'jquery.min' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'underscore-min' %>
  <%= javascript_include_tag 'backbone-min' %>
  <%= javascript_include_tag 'backbone-patch' %>
  <%= javascript_include_tag 'todos' %>

  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag 'todos' %>
  <%- if mobile? %>
    <%= stylesheet_link_tag 'todos-mobile' %>
  <%- end %>

  <%- if iphone? %>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <link rel="apple-touch-icon" href="/images/Check.png" />
  <%- elsif android? %>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%- end %>
</head>
<body>

<%= yield %>

  <%= yield :javascript %>
</body>
</html>

app/views/todos/assets.appcache.erb
CACHE MANIFEST
# Version <%= appcache_version %>

# Javascripts
<%- %w{jquery.min jquery-ui.min underscore-min backbone-min backbone-patch todos}.each do |f| %>
  <%= javascript_path(f) %>
<%- end %>

# Stylesheets
<%- %w{todos}.each do |f| %>
  <%= stylesheet_path(f) %>
<%- end %>

<%- if mobile? %>
  <%= stylesheet_path('todos-mobile') %>
<%- end %>

app/views/todos/index.html.erb
<%- appcache("#{assets_todos_path}.appcache") %>

<h1>Stuff To Do</h1>
<div id="todos">
  <div class="empty">Loading items...</div>

  <div id="incomplete"></div>
  <div id="complete"></div>
</div>

<%- content_for(:javascript) do %>
  <script type="text/javascript">
    var createEditor = function(data) {
      var editor = new TodoEditorView(data);
      editor.render();
    };

    $(function() {
      $.ajax({
        url: '<%= list_todos_path %>.json',
        type: 'post',
        success: createEditor
      });
    });
  </script>
<%- end %>